name: poster_stock
description: A new Flutter project.

publish_to: "none"

version: 1.2.6+44

# Variant: release
# Config: release
# Store: D:\Projects\poster\poster_app\android\upload-keystore.jks
# Alias: upload
# MD5: D4:0A:54:E8:24:74:2D:FD:2D:B4:68:4B:F2:72:29:85
# SHA1: FA:8F:EE:97:C9:06:2F:F3:8D:A4:09:B6:7E:BE:AC:92:9D:C7:38:04
# SHA-256: D1:46:4A:D5:68:55:3C:5E:AE:74:46:12:1C:E1:5E:C4:38:7B:6A:BD:16:BE:C0:29:63:61:4E:93:C7:25:CE:99

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  share_plus: ^7.1.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_riverpod: ^2.3.2
  auto_route: ^7.8.0
  shimmer: ^2.0.0
  package_info_plus: ^6.0.0
  scrollable_positioned_list: ^0.3.8
  sticky_headers: ^0.3.0+2
  photo_manager: ^3.0.0
  url_launcher: ^6.1.11
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  vibration: ^1.8.1
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.0.4
  supertokens_flutter: ^0.2.5
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  sign_in_with_apple: ^5.0.0
  firebase_core: ^3.1.1
  logger: ^2.0.0
  shared_preferences: ^2.2.0
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^15.1.0+1

  transparent_image: ^2.0.1
  async: ^2.11.0
  image: ^4.0.17
  cached_network_image: ^3.2.3
  firebase_crashlytics: ^4.0.2
  path_provider: ^2.1.1
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gap: ^3.0.1 #https://pub.dev/packages/gap
  flutter_easylogger: ^2.3.3 #https://pub.dev/packages/flutter_easylogger
  screenshot: ^3.0.0 #https://pub.dev/packages/screenshot
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.1
  flutter_native_splash: ^2.2.19
  build_runner:

dependency_overrides:
  intl: ^0.18.1

flutter_native_splash:
  background_image: "assets/background.png"
  android_12:
    image: "assets/images/logo.png"
    color: "#010306"

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/launcher_no_bg.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  ios: true
  image_path: "assets/launcher_icon.png"
  macos:
    generate: true
    image_path: "assets/launcher_icon.png"

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
    - family: SF-Pro-Text-IOS
      fonts:
        - asset: fonts/SFProText/SF-Pro-Text-Medium.otf
    - family: SF-Pro-Text
      fonts:
        - asset: fonts/SFProText/SF-Pro-Text-Black.otf
        - asset: fonts/SFProText/SF-Pro-Text-Bold.otf
        - asset: fonts/SFProText/SF-Pro-Text-Heavy.otf
        - asset: fonts/SFProText/SF-Pro-Text-Light.otf
        - asset: fonts/SFProText/SF-Pro-Text-Regular.otf
        - asset: fonts/SFProText/SF-Pro-Text-SemiBold.otf
        - asset: fonts/SFProText/SF-Pro-Text-Thin.otf
        - asset: fonts/SFProText/SF-Pro-Text-Ultralight.otf
    - family: SF-Pro-Display-IOS
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Medium.otf
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Black.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Bold.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Heavy.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Light.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Regular.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-SemiBold.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Thin.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Ultralight.otf
