name: poster_stock
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  flutter_riverpod: ^2.3.2
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner:

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
