name: poster_stock
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  flutter_riverpod: ^2.3.2
  auto_route: ^5.0.4
  shimmer: ^2.0.0
  package_info_plus: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  sticky_headers: ^0.3.0+2
  photo_manager: ^2.6.0
  url_launcher: ^6.1.11
  flutter_screenutil: ^5.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^5.0.3
  flutter_native_splash: ^2.2.19
  build_runner:

flutter_native_splash:
  background_image: "assets/background.png"
  android_12:
    image: "assets/images/logo.png"
    color: "#010306"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  macos:
    generate: true
    image_path: "assets/launcher_icon.png"


flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
    - family: SF-Pro-Text
      fonts:
        - asset: fonts/SFProText/SF-Pro-Text-Black.otf
        - asset: fonts/SFProText/SF-Pro-Text-Bold.otf
        - asset: fonts/SFProText/SF-Pro-Text-Heavy.otf
        - asset: fonts/SFProText/SF-Pro-Text-Light.otf
        - asset: fonts/SFProText/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SFProText/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: fonts/SFProText/SF-Pro-Text-SemiBold.otf
        - asset: fonts/SFProText/SF-Pro-Text-Thin.otf
        - asset: fonts/SFProText/SF-Pro-Text-Ultralight.otf
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Black.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Bold.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Heavy.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Light.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Medium.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Regular.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-SemiBold.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Thin.otf
        - asset: fonts/SFProDisplay/SF-Pro-Display-Ultralight.otf