// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_A5x91wx7KR1n3K_17J76YOFY0W8GsN8',
    appId: '1:405674784124:android:489ccce8f1b8819e1420f9',
    messagingSenderId: '405674784124',
    projectId: 'posterstock-td',
    storageBucket: 'posterstock-td.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-A1ZnM_EQz2oDBmf_JU07vvvVproNWpQ',
    appId: '1:405674784124:ios:31e315529f4ad7c61420f9',
    messagingSenderId: '405674784124',
    projectId: 'posterstock-td',
    storageBucket: 'posterstock-td.appspot.com',
    androidClientId: '405674784124-buqlusrif3nur8sqk7li6u1ruq6votji.apps.googleusercontent.com',
    iosClientId: '405674784124-v0infd39p5s4skn9s89cg57a6i00ferr.apps.googleusercontent.com',
    iosBundleId: 'com.thedirection.posterstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-A1ZnM_EQz2oDBmf_JU07vvvVproNWpQ',
    appId: '1:405674784124:ios:31e315529f4ad7c61420f9',
    messagingSenderId: '405674784124',
    projectId: 'posterstock-td',
    storageBucket: 'posterstock-td.appspot.com',
    androidClientId: '405674784124-buqlusrif3nur8sqk7li6u1ruq6votji.apps.googleusercontent.com',
    iosClientId: '405674784124-v0infd39p5s4skn9s89cg57a6i00ferr.apps.googleusercontent.com',
    iosBundleId: 'com.thedirection.posterstock',
  );
}
